spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dependencydb
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  neo4j:
    uri: bolt://localhost:7687
    authentication:
      username: neo4j
      password: password

logging:
  level:
    root: INFO
    com.enterprise.dependency: DEBUG

# TODO: Externalize sensitive values for production use
